smol-rs/async-executor

src/lib.rs
This allows spawning a task on an executor from outside of it
Fixes #1
=> executor: add spawner

Cargo.toml, benches/executor.rs
Removes the dev dependency on `num_cpus`
=> replace `num_cpus` crate with `std::thread`

src/lib.rs
This PR supersedes #36 by pushing tasks directly to the local runner. A thread-local variable is used to cache a reference to the current `Runner` which is then used by `schedule()` to push tasks directly to the local queue.
This has led to significant improvements in some of our benchmarks! Around 10% in the main use cases, and 77% in the yield now case.
=> alg: Push tasks directly to the local runner, take 2

src/lib.rs, tests/different_executors.rs, tests/local_queue.rs
The bug is invoked as follows:
- Runner 1 is created and stores the current version of the TLS LOCAL_QUEUE variable, which is None.
- Runner 2 is also created. It stores the current version of the TLS variable as well, which is Runner 1's queue.
- Runner 1 is dropped. It stores None into the LOCAL_QUEUE variable.
- Runner 2 tries to run. It reads from the LOCAL_QUEUE variable, sees that it is None, and panics.
This could be solved by just not using the local queue if the variable is None. However, we can do one better; if the slot is open, we can optimize the runner by replacing it with our own queue. This should allow for the local queue to be used more often.
Closes #54
=> Fix a bug where TLS would become None

src/lib.rs
This was added in #37 as an optimization, but has since lead to many bugs. See the issues #53, #57 and #60 for more information. I do not have the bandwidth to address all of these bugs, so I'm taking the path of least resistance by just removing the problematic code.
Closes #53
Closes #57
Closes #60
=> Remove the thread-local executor optimization

Cargo.toml, tests/drop.rs
=> Bump async-io, async-lock and futures-lite

.github/workflows/ci.yml, Cargo.toml
`futures-lite` in the dev dependencies added a `block_on` call that was not present in the WASM build, causing a compile error. This PR makes sure that the `std` feature of `futures-lite` is enabled in Cargo.toml.
This also adds a CI check to ensure that this doesn't happen again.
=> Fix dev-dependency issue on WASM

src/lib.rs, tests/panic_prop.rs
After smol-rs/async-task#37 I meant to add this to the executor. This
commit makes it so all panics are surfaced in the tasks that the user
calls. Hopefully this improves ergonomics.
=> Propagate panics in tasks

Cargo.toml, examples/limit.rs
Whoops, I accidentally reinvented a semaphore and made the example a lot more complicated than it needed to be.
=> Use Semaphore instead of manual event-listener

Cargo.toml
This crate depends on async_task::Builder, which was introduced in 4.4.0
Detected with [cargo-minimal-versions](https://github.com/taiki-e/cargo-minimal-versions)
=> minimum supported async-task version is 4.4.0

src/lib.rs
There's a few atomic variables that really don't need to be, since both Ticker and Runner can be used with exclusive mutable local access.
I don't think this will result in performance improvements per se, but this should at least be more readable.
=> Replace unnecessary atomics with non-atomic operations

src/lib.rs
The fetch of a vacant entry just to get the key then inserting it when spawning tasks works, but does an extra unnecessary Slab lookup. This PR changes it so that the located entry is directly inserted to.
=> Avoid redundant lookups in the active slab when spawning new tasks

src/lib.rs
Meant to be a separate part of #94. The atomic orderings on `State::notified` might be too strong, as it's primarily being used as a deterrent against waking up too many threads. This PR weakens their sequentially consistent operations to Acquire/Release.
=> Weaken the atomic orderings for notification

src/lib.rs
Fix #99. Use `wrapping_add` explicitly to avoid the debug build panic.
=> Use wrapping_add to avoid a panic in debug mode

Cargo.toml, src/lib.rs, tests/larger_tasks.rs
This should catch the errors from earlier.
=> Fix hangs due to tasks being stuck inside of local queues

benches/executor.rs, src/lib.rs, tests/drop.rs, tests/spawn_many.rs
For some workloads many tasks are spawned at a time. This requires
locking and unlocking the executor's inner lock every time you spawn a
task. If you spawn many tasks this can be expensive.
This commit exposes a new "spawn_many" method on both types. This
method allows the user to spawn an entire set of tasks at a time.
Closes #91
=> Add a way to batch spawn tasks

Cargo.toml, src/lib.rs
Fixes #89. Uses @notgull's suggestion of using a `AtomicPtr` with a racy initialization instead of a `OnceCell`.
For the addition of more `unsafe`, I added the `clippy::undocumented_unsafe_blocks` lint at a warn, and fixed a few of the remaining open clippy issues (i.e. `Waker::clone_from` already handling the case where they're equal).
Removing `async_lock` as a dependency shouldn't be a SemVer breaking change.
=> Support racy initialization of an Executor's state

src/lib.rs
Motivation: FallibleTask is part of the public interface of this crate, in that Task::fallible returns FallibleTask. However, in order to name that type, users need to add a direct dependency on async_task and ensure the crates versions are compatible. Reexporting allows crate users to name the type directly.
Thanks!
=> feat: reexport async_task::FallibleTask

benches/executor.rs
This commit aims to add benchmarks that more realistically reflect
workloads that might happen in the real world.
These benchmarks are as follows:
- "channels", which sets up TASKS tasks, where each task uses a channel
to wake up the next one.
- "server", which tries to simulate a web server-type scenario.
=> Add some more filled-out benchmarks

Cargo.toml
=> Bump slab to v0.4.7

Cargo.toml, src/lib.rs
By creating the future manually instead of relying on `async { .. }`, we workaround rustc's inefficient future layouting. On [a simple benchmark](https://github.com/hez2010/async-runtimes-benchmarks-2024) spawning 1M of tasks, this reduces memory use from about 512 bytes per future to about 340 bytes per future.
More context: https://github.com/hez2010/async-runtimes-benchmarks-2024/pull/1
This PR is rebased onto #136 because tests fail otherwise; please consider that PR first. On this PR, the relevant part for review is the second commit.
=> Better memory footprint

CHANGELOG.md, Cargo.toml
Changes:
- Fix build failure with minimal-versions. (#132)
- Prevent executor from becoming unusable by panic of the iterator passed by the user to the `spawn_many`. (#136)
- Reduce memory footprint. (#137)
=> Release 1.13.2
